### PR TITLE
fix #894: oas3-valid-(content-)schema-example has problem with nullable

### LINKED ISSUE #894: oas3-valid-(content-)schema-example: Problem with nullable
**Describe the bug**

It seems that in some cases the rules oas3-valid-schema-example and oas3-valid-content-schema-example fail although the examples are valid. Seems to be an issue with nullable / null values.

I get in the command line:
```
  59:33  error  oas3-valid-content-schema-example  `1` property type should be string
 167:25  error  oas3-valid-content-schema-example  `1` property type should be string
 167:25  error  oas3-valid-schema-example          `1` property type should be string
```

**To Reproduce**

OpenAPI document openapi.yaml:
```
openapi: 3.0.2
info:
  version: 1.0.0
  title: openEO API
  description: ...
  contact:
    name: openEO Consortium
    url: 'http://www.openeo.org'
    email: openeo@list.tuwien.ac.at
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: EO Data Discovery
    description: ...
servers:
  - url: 'https://localhost/api'
    description: ...
paths:
  /collections:
    get:
      summary: Basic metadata for all datasets
      operationId: list-collections
      description: ...
      tags:
        - EO Data Discovery
      responses:
        '200':
          description: A list of collections and related links.
          content:
            application/json:
              schema:
                title: Collections Response
                type: object
                required:
                  - collections
                properties:
                  collections:
                    type: array
                    items:
                      $ref: '#/components/schemas/collection'
                example:
                  collections:
                    - extent:
                        temporal:
                          interval:
                            - - '2000-02-01T00:00:00Z'
                              - null
components:
  schemas:
    collection:
      title: STAC Collection
      type: object
      required:
        - extent
      properties:
        extent:
          type: object
          title: STAC Collection Extent
          description: ...
          required:
            - spatial
            - temporal
          properties:
            temporal:
              description: The *potential* temporal extent of the features in the collection.
              type: object
              properties:
                interval:
                  description: ...
                  type: array
                  minItems: 1
                  items:
                    description: ...
                    type: array
                    minItems: 2
                    maxItems: 2
                    items:
                      type: string
                      format: date-time
                      nullable: true
                    example:
                      - '2011-11-11T12:22:11Z'
                      - null
```

.spectral.yml
```
extends: "spectral:oas"
```

Run: `spectral lint openapi.yaml`

**Expected behavior**

No warnings/errors

**Environment (remove any that are not applicable):**
 - Library version: 5.0.0
 - OS: Windows 10

### PR DESCRIPTION
**Pull request by m-mohr**
Fixes #894.

**Checklist**

- [ ] Tests added / updated
- [ ] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

**Additional context**

This PR tries to solve #894. 
~As the documentation for schemaPath states the sentence below, I guess it's fine to just turn on nullable in ajv without thinking about implications for non OpenAPI documents:~
> ~This may never be useful for anything other than the use-case of checking OpenAPI examples are valid~

### CODE REVIEW

**Comment by m-mohr** [comment]
Can someone help and explain why the change results in an additional "meta-schema not available" in the console? That's why the tests are failing....

**Comment by P0lip** [comment]
@m-mohr 
Try setting `meta` to true https://github.com/stoplightio/spectral/blob/ead745ad981e571331e59ef3f220cc8ba8f22a41/src/functions/schema.ts#L37.
You might also need to remove a couple of `addMetaSchema` calls.
LMK how it goes!

**Comment by m-mohr** [comment]
Thanks, @P0lip. I tried to even use the OpenAPI Schemas to validate the schemas (see commit https://github.com/stoplightio/spectral/pull/914/commits/31fc677c6a99924754c073b822b176c235155e1b) as OpenAPI Schemas != JSON Schema, but couldn't properly test it due to #919 so dropped that effort. 

Now I'm trying the simpler approach and to just get the JSON Schemas / ajv working with nullable, which seems to succeed. I tried to leave the schema function working also for non OpenAPI stuff by incorporating a version switch. I think this is required anyway in the long run when you really want to validate OpenAPI schemas separately from JSON Schemas as they are [not the same](https://phil.tech/api/2018/03/30/openapi-and-json-schema-divergence/) and I guess there will be more issues coming up?!

Let me know what you think about all this.

File: src/functions/schema.ts [hunk 1]
```diff
@@ -33,26 +34,40 @@ const logger = {
...
-ajv._refs['http://json-schema.org/schema'] = 'http://json-schema.org/draft-04/schema';
-
-ajv.addFormat('int32', { type: 'number', validate: oasFormatValidator.int32 });
-ajv.addFormat('int64', { type: 'number', validate: oasFormatValidator.int64 });
-ajv.addFormat('float', { type: 'number', validate: oasFormatValidator.float });
-ajv.addFormat('double', { type: 'number', validate: oasFormatValidator.double });
-ajv.addFormat('byte', { type: 'string', validate: oasFormatValidator.byte });
+const ajvInstances = {};
+
+function getAjv(oasVersion: number = 0): AJV.Ajv {
```
Comment (P0lip) [inline src/functions/schema.ts]:
```suggestion
function getAjv(oasVersion: Optional<number | null>): AJV.Ajv {
```
Perhaps let's make it nullable & optional.

File: src/functions/schema.ts [hunk 2]
```diff
@@ -33,26 +34,40 @@ const logger = {
...
+  if (typeof ajvInstances[oasVersion] !== 'undefined') {
+    return ajvInstances[oasVersion];
+  }
+
+  const ajvOpts: object = {
+    meta: true, // Add default meta schemas (draft 7 at the moment)
+    schemaId: 'auto',
+    jsonPointers: true,
+    unknownFormats: 'ignore',
+    nullable: oasVersion >= 2, // Support nullable for OAS
```
Comment (P0lip) [inline src/functions/schema.ts]:
```suggestion
    nullable: oasVersion === 3, // Support nullable for OAS
```

File: src/functions/schema.ts [hunk 3]
```diff
@@ -33,26 +34,40 @@ const logger = {
...
-ajv._opts.defaultMeta = jsonSpecv4.id;
-// @ts-ignore
-ajv._refs['http://json-schema.org/schema'] = 'http://json-schema.org/draft-04/schema';
-
-ajv.addFormat('int32', { type: 'number', validate: oasFormatValidator.int32 });
-ajv.addFormat('int64', { type: 'number', validate: oasFormatValidator.int64 });
-ajv.addFormat('float', { type: 'number', validate: oasFormatValidator.float });
-ajv.addFormat('double', { type: 'number', validate: oasFormatValidator.double });
-ajv.addFormat('byte', { type: 'string', validate: oasFormatValidator.byte });
+const ajvInstances = {};
```
Comment (P0lip) [inline src/functions/schema.ts]: Since we accept undefined / null, would it make sense to switch to Maps?
Object literals can only take strings and symbols as keys.

File: src/functions/schema.ts [hunk 4]
```diff
@@ -65,7 +80,8 @@ function getSchemaId(schemaObj: JSONSchema): void | string {
 }
 
 const validators = new (class extends WeakMap<JSONSchema, ValidateFunction> {
-  public get(schemaObj: JSONSchema) {
+  public get(schemaObj: JSONSchema, oasVersion: number = 0) {
```
Comment (P0lip) [inline src/functions/schema.ts]:
```suggestion
  public get(schemaObj: JSONSchema, oasVersion: Optional<number>) {
```
Let's just make it optional. 0 looks a tad weird.

File: src/functions/schema.ts [hunk 5]
```diff
@@ -13,6 +12,8 @@ const betterAjvErrors = require('better-ajv-errors/lib/modern');
 
 export interface ISchemaOptions {
   schema: object;
+  // The oasVersion, either 2 or 3 for OpenAPI Spec versions, or undefined / 0 for JSON Schema
```
Comment (P0lip) [inline src/functions/schema.ts]:
```suggestion
  // The oasVersion, either 2 or 3 for OpenAPI Spec versions, or null / 0 for JSON Schema
```
Let's go with null instead of 0.
Thoughts?

File: src/functions/schema.ts (hunk 1 above)
Comment (P0lip) [reply src/functions/schema.ts]: `Optional` can be imported from `@stoplight/types`.

File: src/functions/schema.ts (hunk 2 above)
Comment (m-mohr) [reply src/functions/schema.ts]: Oh, I never realized null is not allowed in Swagger.

File: src/functions/schema.ts (hunk 5 above)
Comment (m-mohr) [reply src/functions/schema.ts]: I chose 0 so that it can be used in the ajvInstances object as key (and because I was confused with how to enforce null as default value in TS).

File: src/functions/schema.ts (hunk 1 above)
Comment (m-mohr) [reply src/functions/schema.ts]: I'll try my best with my limited TS knowledge to make the changes tomorrow.

File: src/functions/schema.ts (hunk 3 above)
Comment (m-mohr) [reply src/functions/schema.ts]: Didn't get it working with maps. So I just use the following as object key `let type : string = (oasVersion && oasVersion >= 2) ? "oas" + oasVersion : "jsonschema";`

File: src/functions/schema.ts (hunk 5 above)
Comment (m-mohr) [reply src/functions/schema.ts]: @P0lip I couldn't get your suggestions working and I'm not familiar with how Optional works, so I tried a bit and the solution committed now works without 0. Please check whether that's okay for you.

**Comment by m-mohr** [comment]
Please fix the build yourself - this annoying lint rule ("Import sources within a group must be alphabetized.") doesn't tell me how I have to order and it always fails regardless of what I try. I tried 20 different cases now!!

File: src/functions/schema.ts [hunk 6]
```diff
@@ -65,7 +81,8 @@ function getSchemaId(schemaObj: JSONSchema): void | string {
 }
 
 const validators = new (class extends WeakMap<JSONSchema, ValidateFunction> {
-  public get(schemaObj: JSONSchema) {
+  public get(schemaObj: JSONSchema, oasVersion?: Optional<number>) {
+    const ajv = getAjv(oasVersion);
```
Comment (nulltoken) [inline src/functions/schema.ts]: @P0lip how cheap is it to recreate a new instance in that layer?

Comment (m-mohr) [reply src/functions/schema.ts]: Only three instances are created, one for each "schema version" (i.e. oas2, oas3 and json schema). So overhead should be minimal and better than creating one ajv instance per example validation.

**Comment by m-mohr** [comment]
> @m-mohr Wow! You're on a roll!

I only want this to be part of our CI workflow ;-) - still worried about #915 though.

File: src/functions/schema.ts (hunk 6 above)
Comment (P0lip) [reply src/functions/schema.ts]: Yeah, it should be cheap.

File: src/functions/schema.ts [hunk 7]
```diff
@@ -33,26 +34,41 @@ const logger = {
...
-ajv.addFormat('byte', { type: 'string', validate: oasFormatValidator.byte });
+const ajvInstances = {};
+
+function getAjv(oasVersion?: Optional<number>): AJV.Ajv {
+  const type: string = oasVersion && oasVersion >= 2 ? 'oas' + oasVersion : 'jsonschema';
+  if (typeof ajvInstances[type] !== 'undefined') {
+    return ajvInstances[type];
+  }
+
+  const ajvOpts: object = {
```
Comment (P0lip) [inline src/functions/schema.ts]:
```suggestion
  const ajvOpts: AJV.Options = {
```
