### PR TITLE
fix(core): update nimma & json-schema

### LINKED ISSUE #1999: Update json-schema dependency in core
**Chore summary**

Update json-schema dependency to > 0.4 as all version below it has security issues.
See: https://github.com/advisories/GHSA-896r-f27r-55mw

**Tasks**
- [ ] Bump json-schema in core

### PR DESCRIPTION
**Pull request by P0lip**
Fixes https://github.com/stoplightio/spectral/issues/1999

**Checklist**

- [x] Tests added / updated
- [x] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

**Additional context**

List of notable changes

- https://github.com/P0lip/nimma/commit/baccfd9fde65d719d7e6ec3dc44756c96ea6ffc1 to address https://stoplight-internal.slack.com/archives/C029YQEEALD/p1639768074075500
- https://github.com/P0lip/nimma/commit/1b4a4d5325545fed62596283ef4287b525cf1434
- https://github.com/P0lip/nimma/commit/5aaf3866cbf87751de5131115e4fb1aee1dc40f1
- https://github.com/P0lip/nimma/commit/e372f8d87f268c6d16de3bc192bcc722e1905762, https://github.com/P0lip/nimma/commit/dd1ed8e8bf2f78374e9f020aeb02e7efc7df3118 - this will be super helpful for me when working on improved errors in Spectral

### CODE REVIEW

File: packages/core/src/runner/runner.ts [hunk 1]
```diff
@@ -96,30 +95,22 @@ function execute(input: unknown, callbacks: Record<string, Callback[]>, jsonPath
...
-      throw e;
-    }
-  }
+  const nimma = new Nimma(jsonPathExpressions, {
+    fallback: jsonPathPlus,
+    unsafe: false,
+    output: 'auto',
+  });
+
+  nimma.query(
```
Comment (P0lip) [inline packages/core/src/runner/runner.ts:104]: in preparation for https://github.com/stoplightio/spectral/tree/feat/cli%2Frich-errors

File: packages/functions/src/__tests__/__helpers__/tester.ts [hunk 2]
```diff
@@ -30,11 +30,26 @@ export default async function <O = unknown>(
...
+      (e as Error & { errors: unknown[] }).errors.length === 1
+    ) {
+      const actualError = (e as Error & { errors: [unknown] }).errors[0];
+      throw actualError instanceof Error && 'cause' in (actualError as Error & { cause?: unknown })
+        ? (actualError as Error & { cause: unknown }).cause
+        : actualError;
+    } else {
+      throw e;
+    }
+  }
```
Comment (P0lip) [inline packages/functions/src/__tests__/__helpers__/tester.ts:54]: hopefully this can be simplified once `AggregateError` and error causes are somehow exposed in standard lib

File: packages/core/src/runner/runner.ts [hunk 3]
```diff
@@ -96,30 +95,22 @@ function execute(input: unknown, callbacks: Record<string, Callback[]>, jsonPath
...
-        return mapped;
-      }, {}),
-    );
-  } catch (e) {
-    if (isAggregateError(e) && e.errors.length === 1) {
-      throw e.errors[0];
-    } else {
-      throw e;
-    }
-  }
```
Comment (P0lip) [inline packages/core/src/runner/runner.ts:124]: in preparation for https://github.com/stoplightio/spectral/tree/feat/cli%2Frich-errors and https://github.com/stoplightio/spectral/tree/chore/validation

File: packages/functions/src/__tests__/__helpers__/tester.ts (hunk 2 above)
Comment (marbemac) [reply packages/functions/src/__tests__/__helpers__/tester.ts:54]: So what's going on here? Don't quite understand this change.

**Review by marbemac — APPROVED** [review]
Have a Q re the change in the test file - otherwise straight forward enough.

File: packages/functions/src/__tests__/__helpers__/tester.ts (hunk 2 above)
Comment (P0lip) [reply packages/functions/src/__tests__/__helpers__/tester.ts:54]: it's to simplify testing.
Assertion of `AggregateError` is shallow, meaning nested `errors` are not checked.
This change makes it so we re-throw a single error so `toThrow` works as expected.
In 99% (if not 100%) of cases we have a single error thrown, so that's why we unpack that AggregateError.
Makes sense?

Comment (P0lip) [reply packages/functions/src/__tests__/__helpers__/tester.ts:54]: Previously we threw a single exception when `AggregateErrors.errors.length === 1`, but I simplified it in the code.
This, however, meant we needed to move that logic in here, but it's a test helper.
