### PR TITLE
fix(ruleset-migrator): occasionally broken length function import

### LINKED ISSUE #1783: length gets imported as length$0
**Describe the bug**

What the title says.

**To Reproduce**

1. Given the following YAML ruleset
```yaml
rules:
  rule:
    given: $
    then:
      function: truthy
  valid-length:
    given: $
    then:
      function: length
```
2. Run migration
3. Get the following output

```
const {
  truthy: truthy,
  length$0: length$0,
} = require("@stoplight/spectral-functions");
module.exports = {
  rules: {
    rule: {
      given: "$",
      then: {
        function: truthy,
      },
    },
    "valid-length": {
      given: "$",
      then: {
        function: length$0,
      },
    },
  },
};
```

**Expected behavior**

```js
const {
  truthy: truthy,
  length: length$0,
} = require("@stoplight/spectral-functions");
module.exports = {
  rules: {
    rule: {
      given: "$",
      then: {
        function: truthy,
      },
    },
    "valid-length": {
      given: "$",
      then: {
        function: length$0,
      },
    },
  },
};
```

Related to https://github.com/stoplightio/platform-internal/issues/7541

### PR DESCRIPTION
**Pull request by P0lip**
Fixes #1783

**Checklist**

- [x] Tests added / updated
- [x] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/ruleset-migrator/src/tree/index.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ export class Tree {
       }
 
       const identifier = Tree.identifier(specifier, scope);
-      existingImportDeclaration.push({ imported: identifier, local: identifier, default: _default });
+      existingImportDeclaration.push({ imported: b.identifier(specifier), local: identifier, default: _default });
```
Comment (P0lip) [inline packages/ruleset-migrator/src/tree/index.ts:57]: We already do it here https://github.com/stoplightio/spectral/blob/f524a8c0a6744127dd878268ac8f6a0d1fc4f889/packages/ruleset-migrator/src/tree/index.ts#L46 but this spot was missed.

**Review by mmiask — APPROVED** [review]
Looks good! 👍
