### PR TITLE
fix(cli): add path to JUnit testcase name

### LINKED ISSUE #2025: JUnit test names are not unique
_Originally posted by @m-denton in https://github.com/stoplightio/spectral/issues/935#issuecomment-576752875:_

> Not sure if this fits here or not but it would also be nice to have the names of these errors appended with a timestamp or other unique identifier (simple number incrementation). This is requested as when loading the junit output into tools like Gitlab CI, if there are multiple juinit entries with the same name, only one of those messages will show in the console. For example, see the following (redacted most of the messages so mismatch on the failure count):
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <testsuites>
> <testsuite package="org.spectral" time="0" tests="103" errors="0" failures="103" name="<classname>.yaml">
> <testcase time="0" name="org.spectral.oas3-valid-content-schema-example" classname="<classname>"><failure message="<message> (oas3-valid-content-schema-example)></failure></testcase>
> <testcase time="0" name="org.spectral.oas3-valid-content-schema-example" classname="<classname>"><failure message="<message> (oas3-valid-content-schema-example)></failure></testcase>
> <testcase time="0" name="org.spectral.oas3-schema" classname="<classname>"><failure message="<message> (oas3-schema) at path #/components/responses/GetPartyTypesOk]]></failure></testcase>
> <testcase time="0" name="org.spectral.oas3-valid-schema-example" classname="<classname>"><failure message="<message> (oas3-valid-schema-example)></failure></testcase>
> <testcase time="0" name="org.spectral.oas3-valid-schema-example" classname="<classname>"><failure message="<message> (oas3-valid-schema-example)></failure></testcase>
> <testcase time="0" name="org.spectral.oas3-valid-schema-example" classname="<classname>"><failure message="<message> (oas3-valid-schema-example)></failure></testcase>
> </testsuite>
> </testsuites>
> ```
> 
> Produces this:
> image
> 
> 
> Notice it shows _3 failed/error test results.._ when in reality, there was 1 true error, then 5 warnings. Since the names are the same in the junit output, Gitlab is bucketing them into the same message which can be deceiving when you may be expecting more warnings/errors.

### PR DESCRIPTION
**Pull request by fgreinacher**
This helps downstream tools disambiguate individual test failures better.

There is no formal spec for the JUnit XML format but JUnit itself does it in a very similar way for dynamic/parametrized tests (see https://github.com/junit-team/junit5/pull/1236).

Fixes #2025.

**Checklist**

- [x] Tests added / updated
- [ ] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

🛠 with ❤ at [Siemens](https://opensource.siemens.io)

### CODE REVIEW

File: packages/cli/src/formatters/junit.ts [hunk 1]
```diff
@@ -46,7 +46,9 @@ export const junit: Formatter = (results, { failSeverity }) => {
       output += `<testsuite package="org.spectral" time="0" tests="${filteredValidationResults.length}" errors="0" failures="${filteredValidationResults.length}" name="${source}">\n`;
 
       for (const result of filteredValidationResults) {
-        output += `<testcase time="0" name="org.spectral.${result.code ?? 'unknown'}" classname="${classname}">`;
+        output += `<testcase time="0" name="org.spectral.${result.code ?? 'unknown'}${
+          result.path.length > 0 ? `(${xmlEscape(result.path.toString())})` : ''
```
Comment (P0lip) [inline packages/cli/src/formatters/junit.ts]: if you want `path` to be more readable, you could use `printPath` from `@stoplight/spectral-runtime`
[Examples](https://github.com/stoplightio/spectral/blob/develop/packages/runtime/src/utils/__tests__/printPath.test.ts)

Comment (fgreinacher) [reply packages/cli/src/formatters/junit.ts]: Good hint, updated!

**Review by P0lip — DISMISSED** [review]

**Comment by P0lip** [comment]
Thanks a bunch for contributing!

**Comment by fgreinacher** [comment]
> Thanks a bunch for contributing!

Happy to help! Did you mean to assign me? If yes, what should I do?

**Comment by P0lip** [comment]
> Happy to help! Did you mean to assign me? If yes, what should I do?

I did, but you don't need to do anything.
It just makes things easier later on to see who contributed a given PR, nothing else than that :)

I'm going to merge the PR soon, just need to figure out why the CI checks haven't been executed yet.

**Comment by P0lip** [comment]
could you actually push some empty commit? this could trigger the workflow

**Comment by fgreinacher** [comment]
> could you actually push some empty commit? this could trigger the workflow

@P0lip I just pushed a merge commit, you need to trigger the workflow again I guess:
 
image

**Comment by P0lip** [comment]
> you need to trigger the workflow again I guess:

I did that, but CircleCI didn't pick it up 🤷‍♂️ 
I'll just merge it in.

**Comment by fgreinacher** [comment]
> > you need to trigger the workflow again I guess:
> 
> I did that, but CircleCI didn't pick it up 🤷‍♂️ I'll just merge it in.

Seems I messed up, hardness tests are failing. I should have read the contributor guide til the end... Working on a fix!
