### PR TITLE
fix(rulesets): oasSchema not using correct dialect for OAS 3.1

### LINKED ISSUE #1752: Incorrect "exclusiveMinimum is not boolean" messages when linting 3.1.0 schema
**Describe the bug**
When linting a simple 3.1.0 schema that includes an `exclusiveMinimum` and `default` value, it seems to work OK, but I get some messages that `exclusiveMinimum is not boolean`. Note that it appears this happens when a `default` value is also specified (if this is removed, the console messages do not appear)
```
OpenAPI 3.x detected
OpenAPI 3.1.x detected
exclusiveMinimum is not boolean
exclusiveMinimum is not boolean
No results with a severity of 'error' or higher found!
```

**To Reproduce**

1. Given this OpenAPI/AsyncAPI document
```
openapi: 3.1.0
info:
  title: Foo
  description: |
    Bar.
  contact:
    name: Foo
    url: https://foo.invalid
  version: 1.2.3
tags:
  - name: foo
    description: bar
servers:
  - url: https://bar.invalid
    description: bar server
paths:
  /foo:
    get:
      summary: foo.
      operationId: foo
      tags:
        - foo
      description: |
        foo
      responses:
        '200':
          $ref: '#/components/responses/Foo'
components:
  responses:
    Foo:
      description: |
        foo.
      content:
        application/json:
          schema:
            type: object
            properties:
              foo:
                type: number
                exclusiveMinimum: 0
                default: 1

```
2. Run this CLI command `npx @stoplight/spectral@6.0.0-alpha3 lint openapi.yaml`
3. See console output above

**Expected behavior**
no `exclusiveMinimum is not boolean` messages printed to the console

**Environment:**
 - Library version: 6.0.0-alpha3
 - OS: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by P0lip**
Fixes https://github.com/stoplightio/spectral/issues/1752

**Checklist**

- [x] Tests added / updated
- [x] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/rulesets/src/oas/functions/oasSchema.ts [hunk 1]
```diff
@@ -27,21 +28,31 @@ export default createRulesetFunction<unknown, Options>(
...
       try {
         if (formats.has(oas2)) {
           schema = convertXNullable({ ...schema });
           traverse(schema, visitOAS2);
-        } else if (formats.has(oas3)) {
+        } else if (formats.has(oas3_0)) {
           schema = convertNullable({ ...schema });
           traverse(schema, visitOAS3);
+        } else if (formats.has(oas3_1)) {
+          if (isPlainObject(context.document.data) && typeof context.document.data.jsonSchemaDialect === 'string') {
```
Comment (P0lip) [inline packages/rulesets/src/oas/functions/oasSchema.ts:42]: we have to respect `jsonSchemaDialect` if there's is any specified.

File: packages/rulesets/src/oas/functions/oasSchema.ts [hunk 2]
```diff
@@ -27,21 +28,31 @@ export default createRulesetFunction<unknown, Options>(
...
+            dialect =
+              (extractDraftVersion(context.document.data.jsonSchemaDialect) as SchemaOptions['dialect']) ??
+              'draft2020-12';
+          } else {
+            dialect = 'draft2020-12';
```
Comment (P0lip) [inline packages/rulesets/src/oas/functions/oasSchema.ts:47]: otherwise use the default for OAS 3.1

**Review by lott-ai — APPROVED** [review]
